### PR TITLE
Create jekyll-gh-pages.yml

### PR DESCRIPTION
**Pull request by Ogwusearch**

### CODE REVIEW

**Comment by Ogwusearch** [comment]
i19iceberg:I19iceberg-patch-1

**Comment by I19iceberg** [comment]
#12

**Comment by I19iceberg** [comment]
#12 i19iceberg:I19iceberg-patch-1

**Review by Ogwusearch — COMMENTED** [review]
.github/workflows/jekyll-gh-pages.yml

**Comment by Ogwusearch** [comment]
Duplicate of #

**Review by Ogwusearch — COMMENTED** [review]
i19iceberg:I19iceberg-patch-1

**Comment by Ogwusearch** [comment]
.github/workflows/jekyll-gh-pages.yml

**Pull request closed without merging**
